### PR TITLE
Handle 429 Status Codes

### PR DESCRIPTION
**Pull request by wdahlenburg**
Description
---------------

After self.fuzzer.pause() is called, self.pausedSemaphore.acquire() is ultimately called. Without releasing the semaphore a deadlock condition occurs.

I added a resume function along with some helper attributes to track state. The self.pausedSemaphore.release() needs to be called on the fuzzer object prior to self.fuzzer.play(). 

I may have short circuited a the "User Cancelled" message by merging the handleInterrupt and handle429 functions, but this should be a step in the right direction. 

Thanks for adding a sample server on https://github.com/maurosoria/dirsearch/pull/504

### CODE REVIEW

**Comment by shelld3v** [comment]
Hi, sorry for the delay, I just read this now. Let me check a little bit before applying everything

**Comment by shelld3v** [comment]
Hi, this is perfect!!! You can now submit this to [maurosoria/dirsearch](https://github.com/maurosoria/dirsearch). But there is a problem: if the user accepts 429 responses, those responses should be filtered:

```python
            if path.status == 429 and not self.accept429:
                self.handle429()

```
To

```python
            if path.status == 429:
                if self.accept429:
                    return
                else:
                    self.handle429()

```

Keep up your good work!!

**Comment by shelld3v** [comment]
Also, there is a bug in this line:

https://github.com/shelld3v/dirsearch/pull/2/files#diff-ca723a004f30c4fe2cad9dcf864d568f1e1b1373cc7893d2e0180ecac8d7df76R513

If the user skips the target, which means he wants to stop on 429, other targets will be missed with the 429 detector!!!

**Comment by shelld3v** [comment]
Hey, the "User Cancelled" message is really important. Please try to remake it!!

**Comment by shelld3v** [comment]
Merge for fun!!!

**Comment by wdahlenburg** [comment]
> Also, there is a bug in this line:
> 
> https://github.com/shelld3v/dirsearch/pull/2/files#diff-ca723a004f30c4fe2cad9dcf864d568f1e1b1373cc7893d2e0180ecac8d7df76R513
> 
> If the user skips the target, which means he wants to stop on 429, other targets will be missed with the 429 detector!!!

Are you referring to line 516 "self.accept429 = True" being the line with a bug in it?

I suppose there two paths. A user can be prompted to set the 429 preference for every site in a list that throws it or they can set the preference after the first occurrence of a 429. What are your thoughts on this?

Personally I'd like to have dirsearch auto-handle pauses, which includes 429s, so the program doesn't hang, but if that shouldn't be the default then a flag could be added in a separate PR.

**Comment by shelld3v** [comment]
What do you think about my simple fix?

**Comment by shelld3v** [comment]
If this has been done, please submit a pull request to [maurosoria/dirsearch](https://github.com/maurosoria/dirsearch)

**Pull request closed without merging**
